### ISSUE TITLE
Database domain

### ISSUE THREAD

**Issue by fxprunayre** [geonetwork/geonetwork#18]
* Migration strategy: Rewamped
* Priority: High
* Dependencies: Databases
* Pull request: 

## Tasks

- Test done with: 
  - [x] H2 (server mode enable) - GN4 and GN5 version of H2 is different
  - [x] Postgresql

- [x] [Spring datasource configuration](https://github.com/GeoCat/geonetwork/blob/main/src/main/resources/application.yml#L45-L56) 
- [x] Database pool use [hikari](https://github.com/brettwooldridge/HikariCP)
- [x] [A new domain layer is created](https://github.com/GeoCat/geonetwork/tree/main/src/main/java/org/geonetwork/domain)
- [ ] Database migration: liquibase? (to check with Joachim, lower priority)

## Database model possible improvements:

* Bug
  * guf_keyword / check error on value column ? h2 only?
* User
  * Remove multiple email support (it can be used for sign in in)
* Metadata
  * uuid column should be unique
* Missing relations
  * operationallowed <> metadata and group and operation
  * metadatarating <> metadata
  * metadatafileuploads <> metadata
  * validation <> metadata
* Missing primary key
  * group_category (fixed in entity)
  * email (fixed in entity)
  * inspireatomfeed (fixed in entity)
* Indexes
  *Add more indexes?
* Table to remove
  * CswServerCapabilitiesInfo
  * HarvestedData
  * Relation
* Sequence
  * Rename rating_criteria_id_seq to use same prefix guf_
  * Rename csw_server_capabilities_info_id_seq to translation_id_seq

**Comment by PascalLike** [comment]
To assign @tanzeeladebont
